#! /usr/bin/bash

# This function checks if Azure CLI is installed on the user's machine, and installs it if not. Following that, it logs in.

setup() {
	if [ ! -d /usr/bin/az ]
	then
	echo "Installing AZURE CLI"
	curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
	fi
	echo "Logging in"
	az login --use-device-code
}

setup
